### PR TITLE
Fixed internal calling order of FindTokenAsync

### PR DESCRIPTION
**Pull request by koenbeuk**
FindAsync expects the first parameter to be the cancellationToken. Currently all calls to FindTokenAsync fail due to it calling FindAsync(params object[] keyValues).

### CODE REVIEW

**Comment by mrahhal** [comment]
Thanks for this.

The CI build failed. From the changes I can see there's a syntax error.
I'll have to confirm this after that.

**Comment by mrahhal** [comment]
Confirmed that this is an actual bug. Please fix the syntax error, I'll merge when the CI build passes.

**Comment by koenbeuk** [comment]
Whoops, all good now

**Review by mrahhal — APPROVED** [review]

**Comment by mrahhal** [comment]
Thanks!

**Pull request merged**
